Minor fixes of MonthPaginator component
laboratoriobridge/bold pull request #603
Opened 2020-09-18 20:17 UTC by calistro

- [x] Creating `ghost` prop, which remove the box around the component;
- [x] Using hook `usePopper` to make the month selection a popper;
- [x] Some I18n fixes;

2020-09-18 21:07 UTC, gisabernardess reviewed
Tá lindu :heart:

2020-09-18 21:07 UTC, gisabernardess commented on src/components/MonthPaginator/MonthPaginator.tsx
>      margin: '0.25rem 0.25rem',
acho que isso foi erro meu né, mas dá pra deixar apenas uma vez o `0.25rem` também :rofl:

2020-09-18 21:07 UTC, gisabernardess commented on src/components/MonthPaginator/MonthPaginator.tsx
> +    margin: '0.25rem 0 0.25rem 0',
aqui dá pra deixar `'0.25rem 0'` que é a mesma coisa :grin: 
pra lembrar eu sempre uso a sequencia: `top - right - bottom - left` , que é o valor de cada.
aí deixando dois valores fica a sequencia: `top/bottom - right/left`

2020-09-18 21:25 UTC, calistro commented on src/components/MonthPaginator/MonthPaginator.tsx
> +    margin: '0.25rem 0 0.25rem 0',
Eu sempre esqueço de ir refinando isso, que as vezes vou arrumando as margens de um lado e do outro e quando vejo fica tudo simétrico e esqueço de fazer assim. kkkkk

2020-09-18 22:45 UTC, gisabernardess approved these changes

2020-09-21 12:49 UTC, gisabernardess approved these changes

2020-09-21 16:42 UTC, Andrevmatias requested changes
Só detalhezinhos. Nem tá feio o CSS :laughing:

2020-09-21 16:42 UTC, Andrevmatias commented on src/components/MonthPaginator/MonthPaginator.tsx
> +    borderTop: `0px`,
'0' não usa unidade de medida :wink:

2020-09-21 16:42 UTC, Andrevmatias commented on src/components/MonthPaginator/MonthPaginator.tsx
> +    margin: '0.25rem 0.25rem',
```suggestion
    margin: '0.25rem',
```

2020-09-21 18:50 UTC, calistro commented on src/components/MonthPaginator/MonthPaginator.tsx
> +  popperPlacement?: Placement
Conforme conversamos será criado uma outra issue para tratar dessa exposição de props de lib internas.

2020-09-21 19:00 UTC, Andrevmatias approved these changes
Tope!

2020-09-21 19:13 UTC, merged