Fixing the clear of MonthRangePicker
laboratoriobridge/bold pull request #644
Opened 2021-03-02 17:07 UTC by zDudaHang

Fixing the problem of not clearing the input value when clicking on the 'x' of the MonthRangePicker

2021-03-02 17:35 UTC, gustavomoser approved these changes

2021-03-03 16:59 UTC, lucasjoao requested changes
:top:  

Só verificar alguns comentários de dúvida e melhorias

2021-03-03 16:59 UTC, lucasjoao commented on src/components/MonthRangePicker/MonthRangePicker.test.tsx
> +        const span = container.querySelectorAll('span[title="Clear"]')[0]
Detalhe, mas aqui poderia trocar o `0` pela constante do arquivo `FIRST_INPUT` na tentativa de manter padronizado essa classe de teste.

2021-03-03 16:59 UTC, lucasjoao commented on src/components/MonthRangePicker/MonthRangePicker.test.tsx
> +        const span = container.querySelectorAll('span[title="Clear"]')[1]
Detalhe, mas aqui poderia trocar o `1` pela constante do arquivo `SECOND_INPUT` na tentativa de manter padronizado essa classe de teste.

2021-03-03 16:59 UTC, lucasjoao commented on src/components/MonthRangePicker/MonthRangePicker.tsx
> +      : onChange({ startDate: undefined, endDate: endDate })
Fiquei um pouco em dúvida: o `transformRangeReferenceMonth` já não faz isso e retorna `undefined` quando não existir um `start` ou `end`? Com isso, não daria para substituir isso tudo para `onChange({ startDate: startDate, endDate: endDate })`?  Ou tem alguma magia do js acontecendo aqui que eu não percebi? :joy:

2021-03-03 16:59 UTC, lucasjoao commented on src/components/MonthRangePicker/util.tsx
> +  endDate: range.end ? new Date(range.end.year, range.end.month + 1, 0, 0, 0, 0) : undefined,
Uma dúvida, o + 1 é para realizar o comportamento correto no componente de selecionar 1 mês a mais?

2021-03-03 17:29 UTC, zDudaHang commented on src/components/MonthRangePicker/util.tsx
> +  endDate: range.end ? new Date(range.end.year, range.end.month + 1, 0, 0, 0, 0) : undefined,
É para pegar o último dia do mês do range.end.month

2021-03-04 11:46 UTC, zDudaHang commented on src/components/MonthRangePicker/MonthRangePicker.tsx
> +      : onChange({ startDate: undefined, endDate: endDate })
Meu deus, é verdade haha

2021-03-04 14:19 UTC, lucasjoao approved these changes
:rocket:

2021-03-04 16:46 UTC, merged