Fix dropdown closing inside a modal
laboratoriobridge/bold pull request #720
Opened 2021-12-14 17:59 UTC by wesleydecezere

2021-12-14 19:01 UTC, wagnerbsantos approved these changes

2021-12-14 22:30 UTC, lucasjoao requested changes
Please check the broken tests and I'm curious, what's the problem that you're solving?

2021-12-16 22:17 UTC, wesleydecezere commented
> Please check the broken tests and I'm curious, what's the problem that you're solving?

The problem description has been added to the issue #719 and the snapshots have been updated.

2021-12-17 15:09 UTC, lucasjoao submitted a review, later dismissed
:rocket:

2021-12-17 16:08 UTC, diegoasmello approved these changes

2022-01-05 14:03 UTC, continMarcelo approved these changes

2022-01-05 14:04 UTC, merged