[TextArea] fix alignment between errorText and maxLength on TextArea
laboratoriobridge/bold pull request #794
Opened 2023-05-11 19:08 UTC by rafatillmann

2023-05-11 21:55 UTC, lucasjoao requested changes
Great! Just one doubt to check.

2023-05-11 21:55 UTC, lucasjoao commented on src/components/TextArea/TextArea.tsx
> +        </div>
Isn't showing a empty `div` if doesn't have `error`? 

Maybe in this way fix this:

```suggestion
	{error && (
		<div>
			<FormError id={errorId} role='alert'>
				{error}
			</FormError>
		</div>
	)}
```

2023-05-16 15:58 UTC, LeonardoVieiraNunes approved these changes

2023-05-16 16:47 UTC, marianadick approved these changes

2023-05-16 17:17 UTC, merged