851 -  [Chart] Allow to use stroke line without dashes
laboratoriobridge/bold pull request #852
Opened 2024-09-10 19:27 UTC by AndresKindel

closes  #851

2024-09-11 20:33 UTC, wesleydecezere submitted a review, later dismissed

2024-09-11 21:43 UTC, GuilhermePrandi submitted a review, later dismissed

2024-09-12 13:12 UTC, wagnerbsantos approved these changes

2024-09-12 13:25 UTC, zDudaHang approved these changes

2024-09-12 13:25 UTC, zDudaHang commented on src/components/Chart/Chart.stories.tsx
> +    dashed: true,
```suggestion
    dashed: false,
```
I think it's important to show all options at storybook

2024-09-12 20:48 UTC, Andrevmatias requested changes
Great! 

Just take into account that this component must follow the bold rules for [data visualization](https://bold.bridge.ufsc.br/en/design-guidelines/data-visualization/usage). I think it would be really good to evolve the specification in the bold's site/prototyte to better define the uses and resources of the reference area.

2024-09-12 20:48 UTC, Andrevmatias commented on src/components/Chart/model.ts
> +  dashed?: boolean
```suggestion
  strokeType?: 'line' | 'dashed'
```
It's more explicit and scalable

2024-09-16 13:29 UTC, wagnerbsantos approved these changes

2024-09-17 16:50 UTC, Andrevmatias approved these changes
Great! :blush:

2024-09-23 22:03 UTC, merged